import os
import sys
import subprocess

# Auto-install dependencies if missing
try:
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement, parse_xml
    from docx.oxml.ns import qn, nsdecls
except ImportError:
    print("Installing python-docx dependency...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-docx"])
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement, parse_xml
    from docx.oxml.ns import qn, nsdecls

import re

def set_cell_background(cell, color_hex):
    shading_xml = f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>'
    cell._tc.get_or_add_tcPr().append(parse_xml(shading_xml))

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(m)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)

def set_cell_left_border(cell, color_hex, size_pt=24):
    tcPr = cell._tc.get_or_add_tcPr()
    tcBorders = OxmlElement('w:tcBorders')
    
    # Left border
    left = OxmlElement('w:left')
    left.set(qn('w:val'), 'single')
    left.set(qn('w:sz'), str(size_pt)) # 24 = 3pt
    left.set(qn('w:space'), '0')
    left.set(qn('w:color'), color_hex)
    tcBorders.append(left)
    
    # Clear others
    for b in ['top', 'bottom', 'right']:
        node = OxmlElement(f'w:{b}')
        node.set(qn('w:val'), 'nil')
        tcBorders.append(node)
        
    tcPr.append(tcBorders)

def build_docx(markdown_text, output_path, theme_color_hex="7B4E2E"):
    doc = docx.Document()
    
    # Theme colors
    primary_color = RGBColor(int(theme_color_hex[0:2], 16), int(theme_color_hex[2:4], 16), int(theme_color_hex[4:6], 16))
    text_color = RGBColor(0x2D, 0x24, 0x1C)
    muted_color = RGBColor(0x6C, 0x59, 0x46)
    
    # Page setup - Margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Simple Markdown Parser
    lines = markdown_text.split('\n')
    in_list = False
    in_table = False
    table_rows = []
    
    # Title metadata
    title_text = "Document"
    subtitle_text = "Generated by Nexon AI"
    
    # Try to find custom metadata
    for line in lines[:5]:
        m = re.match(r'^title:\s*(.*)$', line, re.IGNORECASE)
        if m:
            title_text = m.group(1).strip()
        m = re.match(r'^subtitle:\s*(.*)$', line, re.IGNORECASE)
        if m:
            subtitle_text = m.group(1).strip()

    # Create Cover Header
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(24)
    title_p.paragraph_format.space_after = Pt(4)
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run(title_text)
    title_run.font.name = 'Georgia'
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = primary_color

    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(36)
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub_p.add_run(subtitle_text)
    sub_run.font.name = 'Arial'
    sub_run.font.size = Pt(11)
    sub_run.font.italic = True
    sub_run.font.color.rgb = muted_color

    # Add divider line
    div_p = doc.add_paragraph()
    div_p.paragraph_format.space_after = Pt(24)
    div_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    div_run = div_p.add_run("—" * 32)
    div_run.font.color.rgb = muted_color

    for line in lines:
        line_str = line.strip()
        if not line_str:
            continue
            
        # Ignore metadata in content body
        if re.match(r'^(title|subtitle):', line_str, re.IGNORECASE):
            continue

        # Close list if not in list line
        if in_list and not line_str.startswith(('-', '*', '1.', '2.', '3.', '4.', '5.')):
            in_list = False

        # Close table if not in table line
        if in_table and not line_str.startswith('|'):
            in_table = False
            # Render Table
            if len(table_rows) > 0:
                cols_count = max(len(r) for r in table_rows)
                t = doc.add_table(rows=len(table_rows), cols=cols_count)
                t.autofit = True
                for row_idx, r_data in enumerate(table_rows):
                    row = t.rows[row_idx]
                    is_header = (row_idx == 0)
                    for col_idx, cell_val in enumerate(r_data):
                        if col_idx >= len(row.cells):
                            continue
                        cell = row.cells[col_idx]
                        cell.text = cell_val.strip()
                        set_cell_margins(cell, top=120, bottom=120, left=180, right=180)
                        
                        # Style headers
                        if is_header:
                            set_cell_background(cell, theme_color_hex)
                            for run in cell.paragraphs[0].runs:
                                run.font.bold = True
                                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                                run.font.size = Pt(10.5)
                        else:
                            # Striped shading
                            if row_idx % 2 == 1:
                                set_cell_background(cell, "FBF9F6")
                            for run in cell.paragraphs[0].runs:
                                run.font.size = Pt(10)
                                run.font.color.rgb = text_color
                doc.add_paragraph() # spacing after table
                table_rows = []

        # Heading 1
        if line_str.startswith('# '):
            h_text = line_str[2:].strip()
            h = doc.add_paragraph()
            h.paragraph_format.space_before = Pt(20)
            h.paragraph_format.space_after = Pt(6)
            run = h.add_run(h_text)
            run.font.name = 'Georgia'
            run.font.size = Pt(18)
            run.font.bold = True
            run.font.color.rgb = primary_color
            
        # Heading 2
        elif line_str.startswith('## '):
            h_text = line_str[3:].strip()
            h = doc.add_paragraph()
            h.paragraph_format.space_before = Pt(14)
            h.paragraph_format.space_after = Pt(4)
            run = h.add_run(h_text)
            run.font.name = 'Georgia'
            run.font.size = Pt(14)
            run.font.bold = True
            run.font.color.rgb = primary_color
            
        # Heading 3
        elif line_str.startswith('### '):
            h_text = line_str[4:].strip()
            h = doc.add_paragraph()
            h.paragraph_format.space_before = Pt(10)
            h.paragraph_format.space_after = Pt(2)
            run = h.add_run(h_text)
            run.font.name = 'Arial'
            run.font.size = Pt(12)
            run.font.bold = True
            run.font.color.rgb = muted_color

        # Bullet List Items
        elif line_str.startswith(('-', '*')):
            item_text = line_str[1:].strip()
            p = doc.add_paragraph(style='List Bullet')
            p.paragraph_format.space_after = Pt(3)
            run = p.add_run(item_text)
            run.font.name = 'Arial'
            run.font.size = Pt(11)
            run.font.color.rgb = text_color
            in_list = True

        # Numbered List Items
        elif re.match(r'^\d+\.', line_str):
            item_text = re.sub(r'^\d+\.', '', line_str).strip()
            p = doc.add_paragraph(style='List Number')
            p.paragraph_format.space_after = Pt(3)
            run = p.add_run(item_text)
            run.font.name = 'Arial'
            run.font.size = Pt(11)
            run.font.color.rgb = text_color
            in_list = True

        # Callout box block (starts with >)
        elif line_str.startswith('>'):
            callout_text = line_str[1:].strip()
            t = doc.add_table(rows=1, cols=1)
            t.autofit = True
            cell = t.cell(0, 0)
            cell.text = callout_text
            set_cell_background(cell, "FAF5EE")
            set_cell_left_border(cell, theme_color_hex, size_pt=24) # 3pt thick left border
            set_cell_margins(cell, top=140, bottom=140, left=200, right=200)
            
            p = cell.paragraphs[0]
            for run in p.runs:
                run.font.name = 'Arial'
                run.font.size = Pt(10.5)
                run.font.italic = True
                run.font.color.rgb = muted_color
            doc.add_paragraph() # space after callout

        # Table rows
        elif line_str.startswith('|'):
            # Ignore separators like |---|---|
            if re.match(r'^\|[\s:-|]*$', line_str):
                continue
            cells = [c.strip() for c in line_str.split('|')[1:-1]]
            table_rows.append(cells)
            in_table = True

        # Standard Paragraph
        else:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(8)
            p.paragraph_format.line_spacing = 1.15
            run = p.add_run(line_str)
            run.font.name = 'Arial'
            run.font.size = Pt(11)
            run.font.color.rgb = text_color

    # Save document
    doc.save(output_path)
    print(f"Success: Saved document to {output_path}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python3 generate_docx.py <input_md_path> <output_docx_path> [theme_color_hex]")
        sys.exit(1)
        
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    theme_color = sys.argv[3] if len(sys.argv) > 3 else "7B4E2E"
    
    with open(input_path, 'r', encoding='utf-8') as f:
        text = f.read()
        
    build_docx(text, output_path, theme_color)
